"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['../mDraw.py']
DATA_FILES = ['./avrdude','../avrdude.mac.conf','./potrace','../XY.hex','../mScara.hex','../mSpider.hex','../mEggBot.hex','../mCar.hex']
OPTIONS = {
'argv_emulation': True,
'iconfile':'mDraw.icns',
"includes" : ["sip"],
"packages" : ["PyQt5", "importlib"]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)